### ISSUE TITLE
VintageFix and MUL Redirects Targeting Same Methods Crash

### ISSUE THREAD

**Issue by NaxefirYT** [Elephant1214/MuteUselessLogs#1]
[2024-01-26-7.log](https://github.com/Elephant1214/MuteUselessLogs/files/14063487/2024-01-26-7.log)

**Comment by Elephant1214** [comment]
Oddly enough this works fine for me with VintageFix, although it could be OptiFine tomfoolery because I had to modify it to work with OF in the first place. I think changing priority will fix it, I'll do that and send the new jar to see if it'll fix your issue.
